title: "Cyber Portfolio"
baseurl: "" # Deixe vazio se for seunome.github.io, ou "/nome-do-repo" se for um subdiretório
url: "https://0xk4z.github.io"
markdown: kramdown
theme: minima # Apenas para evitar erros, mas usaremos CSS própriob
sass:
  quiet_deps: true
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  articles:
    output: true
    permalink: /articles/:title/
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: true
  per_page: 4
  # Configuração para Writeups
  collection: ['writeups', 'articles']
  extension: 'html'
  index_limit: 0