title: "Cyber Portfolio"
baseurl: "" # Deixe vazio se for seunome.github.io, ou "/nome-do-repo" se for um subdiretório
url: "https://0xk4z.github.io"
markdown: kramdown
theme: minima # Apenas para evitar erros, mas usaremos CSS própriob
sass:
  quiet_deps: true
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  articles:
    output: true
    permalink: /articles/:title/
plugins:
  - jekyll-paginate-v2
  - jekyll-minifier

pagination:
  enabled: true
  per_page: 4
  title: ":title - Page :num"
  permalink: "page/:num/"
  # Configuração para Writeups
  collection: ['writeups', 'articles']
  extension: 'html'
  index_limit: 0

jekyll-minifier:
  remove_comments: true             # Default: true
  remove_input_attributes: true    # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_multi_spaces: true         # Default: true
  compress_js_templates: true      # Default: false