title: "Cyber Portfolio"
baseurl: "" # Deixe vazio se for seunome.github.io, ou "/nome-do-repo" se for um subdiretório
url: "https://0xk4z.github.io"
markdown: kramdown
theme: minima # Apenas para evitar erros, mas usaremos CSS própriob
sass:
  quiet_deps: true
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  articles:
    output: true
    permalink: /articles/:title/
plugins:
  - jekyll-paginate-v2
  - jekyll-minifier

pagination:
  enabled: true
  per_page: 4
  title: ":title - Page :num"
  permalink: "page/:num/"
  # Configuração para Writeups
  collection: ['writeups', 'articles']
  extension: 'html'
  index_limit: 0

autopages:
  enabled: true
  tags:
    enabled: true
    layouts: 
      - autopage_tags.html # Vamos criar este arquivo agora
    permalink: "/tag/:tag/"

  collections:
    enabled: false # Desative isso para evitar duplicidade

jekyll-minifier:
  remove_comments: true             
  remove_input_attributes: true    
  compress_css: true                
  compress_javascript: true         
  compress_json: true               
  remove_intertag_spaces: true      
  remove_multi_spaces: true
  compress_js_templates: true